apiVersion: batch/v1
kind: Job
metadata:
    name: dumb-job-job
    namespace: microservices
spec:
    template:
        metadata:
            namespace: microservices
        spec:
            containers:
                -   name: clown-parade
                    image: dhinojosa/dumb-job
            restartPolicy: Never
    backoffLimit: 4
